# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: constraints.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'constraints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from protobuf_pydantic_gen import pydantic_pb2 as protobuf__pydantic__gen_dot_pydantic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63onstraints.proto\x12\x13\x63onstraints_example\x1a google/protobuf/descriptor.proto\x1a$protobuf_pydantic_gen/pydantic.proto\"\xc3\x01\n\x14\x43onfidenceAssessment\x12\x44\n\x0bself_report\x18\x01 \x01(\x02\x42/\xaa\xbb\x18+\n\x16\xe4\xb8\xbb\xe8\xa7\x82\xe4\xbf\xa1\xe5\xbf\x83 0.0\xe2\x80\x93\x31.0y\x00\x00\x00\x00\x00\x00\x00\x00\x89\x01\x00\x00\x00\x00\x00\x00\xf0?\x12\x1e\n\x05score\x18\x02 \x01(\x01\x42\x0f\xaa\xbb\x18\x0b\n\traw score\x12\x45\n\x05stage\x18\x03 \x01(\x0e\x32!.constraints_example.MasteryStageB\x13\xaa\xbb\x18\x0f\n\rmastery stage*w\n\x0cMasteryStage\x12\x1d\n\x19MASTERY_STAGE_UNSPECIFIED\x10\x00\x12\x08\n\x04SEEN\x10\x01\x12\x0e\n\nUNDERSTOOD\x10\x02\x12\r\n\tRETRIEVED\x10\x03\x12\x11\n\rCONSOLIDATING\x10\x04\x12\x0c\n\x08MASTERED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'constraints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIDENCEASSESSMENT'].fields_by_name['self_report']._loaded_options = None
  _globals['_CONFIDENCEASSESSMENT'].fields_by_name['self_report']._serialized_options = b'\252\273\030+\n\026\344\270\273\350\247\202\344\277\241\345\277\203 0.0\342\200\2231.0y\000\000\000\000\000\000\000\000\211\001\000\000\000\000\000\000\360?'
  _globals['_CONFIDENCEASSESSMENT'].fields_by_name['score']._loaded_options = None
  _globals['_CONFIDENCEASSESSMENT'].fields_by_name['score']._serialized_options = b'\252\273\030\013\n\traw score'
  _globals['_CONFIDENCEASSESSMENT'].fields_by_name['stage']._loaded_options = None
  _globals['_CONFIDENCEASSESSMENT'].fields_by_name['stage']._serialized_options = b'\252\273\030\017\n\rmastery stage'
  _globals['_MASTERYSTAGE']._serialized_start=312
  _globals['_MASTERYSTAGE']._serialized_end=431
  _globals['_CONFIDENCEASSESSMENT']._serialized_start=115
  _globals['_CONFIDENCEASSESSMENT']._serialized_end=310
# @@protoc_insertion_point(module_scope)
