# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   constant_model.py
@Time    :   2026-06-26 18:09:47
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

from enum import IntEnum as _IntEnum
from protobuf_pydantic_gen.ext import GenericEnumType


class ExampleType(_IntEnum):
    UNKNOWN = 0
    TYPE1 = 1
    TYPE2 = 2
    TYPE3 = 3


ExampleTypeType = GenericEnumType(
    ExampleType,
    storage_mode="value",
    read_modes=("value", "name"),
)

ExampleTypeNameType = GenericEnumType(
    ExampleType,
    storage_mode="name",
    read_modes=("name", "value"),
)
