# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   constant_model.py
@Time    :   2026-03-22 09:46:39
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from enum import Enum as _Enum
from protobuf_pydantic_gen.ext import GenericEnumType


class ExampleType(_Enum):
    UNKNOWN = 0
    TYPE1 = 1
    TYPE2 = 2
    TYPE3 = 3


ExampleTypeType = GenericEnumType(ExampleType)
