# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   constraints_model.py
@Time    :   2026-06-26 18:09:47
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

from enum import IntEnum as _IntEnum
from google.protobuf import message as _message, message_factory
from protobuf_pydantic_gen.ext import (
    GenericEnumType,
    model2protobuf,
    pool,
    protobuf2model,
)
from pydantic import BaseModel, ConfigDict, Field as _Field
from typing import Optional, Type


class MasteryStage(_IntEnum):
    MASTERY_STAGE_UNSPECIFIED = 0
    SEEN = 1
    UNDERSTOOD = 2
    RETRIEVED = 3
    CONSOLIDATING = 4
    MASTERED = 5


MasteryStageType = GenericEnumType(
    MasteryStage,
    storage_mode="value",
    read_modes=("value", "name"),
)

MasteryStageNameType = GenericEnumType(
    MasteryStage,
    storage_mode="name",
    read_modes=("name", "value"),
)


class ConfidenceAssessment(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    self_report: Optional[float] = _Field(
        description="主观信心 0.0–1.0", ge=0.0, le=1.0, default=0.0
    )
    score: Optional[float] = _Field(description="raw score", default=0.0)
    stage: Optional["MasteryStage"] = _Field(
        description="mastery stage", default=MasteryStage(0)
    )

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("constraints_example.ConfidenceAssessment")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ConfidenceAssessment":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


ConfidenceAssessment.model_rebuild()
