# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   example_model.py
@Time    :   2026-03-22 09:46:39
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

import datetime
from .constant_model import ExampleType, ExampleTypeType
from .example2_model import Example2
from google.protobuf import message as _message, message_factory
from pgvector.sqlalchemy import Vector
from protobuf_pydantic_gen.ext import model2protobuf, pool, protobuf2model
from pydantic import BaseModel, ConfigDict, Field as _Field
from sqlalchemy import Integer, TIMESTAMP
from sqlalchemy.dialects.postgresql import JSON
from sqlmodel import Column, Field, PrimaryKeyConstraint, SQLModel, UniqueConstraint
from typing import Any, Dict, List, Optional, Type


class Nested(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    name: Optional[str] = _Field(
        description="Name of the example",
        default="John Doe",
        alias="full_name",
        max_length=128,
        json_schema_extra={"example": "ohn Doe"},
    )

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("pydantic_example.Nested")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "Nested":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class Example(SQLModel, table=True):
    __tablename__ = "example_table"  # type: ignore[assignment]
    __table_args__ = (
        UniqueConstraint("name", "age", name="uni_name_age"),
        PrimaryKeyConstraint("name", name="index_name"),
        {"extend_existing": True},
    )
    name: Optional[str] = Field(
        description="Name of the example",
        default="John Doe",
        alias="full_name",
        sa_column_kwargs={"comment": "Name of the example"},
        schema_extra={"label": "名称"},
    )
    age: Optional[int] = Field(
        description="Age of the example",
        default=30,
        alias="years",
        sa_column_kwargs={"comment": "Age of the example"},
        schema_extra={"label": "年龄"},
    )
    emails: Optional[List[str]] = Field(
        description="Emails of the example",
        default=["example@example.com", "example2@example.com"],
        sa_column=Column(JSON, doc="Emails of the example"),
    )
    examples: Optional[List[Example2]] = Field(
        description="Nested message",
        default=[],
        sa_column=Column(JSON, doc="Nested message"),
    )
    entry: Optional[Dict[str, Any]] = Field(
        description="Properties of the example",
        default={},
        sa_column=Column(JSON, doc="Properties of the example"),
    )
    nested: Optional[Nested] = Field(
        description="Nested message",
        default=None,
        sa_column=Column(JSON, doc="Nested message"),
    )
    created_at: datetime.datetime = Field(
        description="Creation date of the example",
        default_factory=datetime.datetime.now,
        sa_column=Column(
            TIMESTAMP(timezone=True), nullable=True, doc="Creation date of the example"
        ),
    )
    type: Optional[ExampleType] = Field(
        description="Type of the example",
        default=ExampleType.TYPE1,
        sa_column=Column(ExampleTypeType, nullable=False, doc="Type of the example"),
    )
    score: Optional[float] = Field(
        description="Score of the example",
        default=0.0,
        le=100.0,
        sa_column=Column(Integer, doc="Score of the example"),
    )
    metadatas: Optional[Dict[str, Any]] = Field(
        description="Metadata attributes and their values for the document",
        default=None,
        sa_column=Column(
            JSON, doc="Metadata attributes and their values for the document"
        ),
    )
    embeddings: Optional[List[float]] = Field(
        description="Embedding vector for the example",
        default=[],
        sa_column=Column(Vector(1563), doc="Embedding vector for the example"),
    )

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("pydantic_example.Example")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "Example":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)
