"""
Auto-generated anti-corruption layer for ORM table models.

Business code should import table classes from this module
instead of referencing generated model files directly.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from .example_model import Example as ExampleRow  # noqa: F401

__all__ = [
    "ExampleRow",
]
