# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: constant.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63onstant.proto\x12\x10pydantic_example*;\n\x0b\x45xampleType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05TYPE1\x10\x01\x12\t\n\x05TYPE2\x10\x02\x12\t\n\x05TYPE3\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'constant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXAMPLETYPE']._serialized_start=36
  _globals['_EXAMPLETYPE']._serialized_end=95
# @@protoc_insertion_point(module_scope)
