# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example2.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import constant_pb2 as constant__pb2
from protobuf_pydantic_gen import pydantic_pb2 as protobuf__pydantic__gen_dot_pydantic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xample2.proto\x12\x10pydantic_example\x1a\x0e\x63onstant.proto\x1a$protobuf_pydantic_gen/pydantic.proto\"e\n\x08\x45xample2\x12Y\n\x04type\x18\x01 \x01(\x0e\x32\x1d.pydantic_example.ExampleTypeB,\xaa\xbb\x18(\n\x13Type of the example\x1a\x11\x45xampleType.TYPE1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXAMPLE2'].fields_by_name['type']._options = None
  _globals['_EXAMPLE2'].fields_by_name['type']._serialized_options = b'\252\273\030(\n\023Type of the example\032\021ExampleType.TYPE1'
  _globals['_EXAMPLE2']._serialized_start=90
  _globals['_EXAMPLE2']._serialized_end=191
# @@protoc_insertion_point(module_scope)
